import { useState, type FormEvent } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Clock, Pencil, Plus } from "lucide-react";
import { api, errorMessage } from "../lib/api";
import { formatMoney } from "../lib/utils";
import type { ClinicService, ClinicServiceInput } from "../types/api";
import { PageHeader } from "../components/page-header";
import { Card } from "../components/ui/card";
import { Button } from "../components/ui/button";
import { Dialog } from "../components/ui/dialog";
import { Input } from "../components/ui/input";
import { EmptyState, ErrorState, LoadingState } from "../components/feedback";

export function ServicesPage(){const query=useQuery({queryKey:["services"],queryFn:()=>api<ClinicService[]>("/api/services")});const[editing,setEditing]=useState<ClinicService|null|"new">(null);return <><PageHeader title="Услуги" description="Прайс-лист и длительность процедур" actions={<Button onClick={()=>setEditing("new")}><Plus size={17}/>Новая услуга</Button>}/>{query.isLoading?<LoadingState/>:query.error?<ErrorState error={query.error}/>:!query.data?.length?<EmptyState title="Услуг нет" text="Добавьте первую услугу"/>:<Card className="overflow-x-auto"><table className="w-full min-w-[720px] text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr>{["Услуга","Длительность","Цена","Статус","Действия"].map(h=><th className="px-5 py-3" key={h}>{h}</th>)}</tr></thead><tbody>{query.data.map(service=><ServiceRow key={service.id} service={service} edit={()=>setEditing(service)}/>)}</tbody></table></Card>}<ServiceDialog value={editing} close={()=>setEditing(null)}/></>}
function ServiceRow({service,edit}:{service:ClinicService;edit:()=>void}){const client=useQueryClient();const mutation=useMutation({mutationFn:()=>api<ClinicService>(`/api/services/${service.id}`,{method:"PUT",body:JSON.stringify({...service,active:!service.active})}),onSuccess:()=>client.invalidateQueries({queryKey:["services"]})});return <tr className="border-t border-slate-100"><td className="px-5 py-4 font-medium">{service.name}</td><td className="px-5 py-4 text-slate-600"><span className="flex items-center gap-1.5"><Clock size={15}/>{service.durationMinutes} мин</span></td><td className="px-5 py-4 font-semibold">{formatMoney(service.price)}</td><td className="px-5 py-4"><span className={service.active?"rounded-full bg-emerald-50 px-2 py-1 text-xs text-emerald-700":"rounded-full bg-slate-100 px-2 py-1 text-xs text-slate-600"}>{service.active?"Активна":"Неактивна"}</span></td><td className="px-5 py-4"><div className="flex gap-2"><Button size="sm" variant="secondary" onClick={edit}><Pencil size={15}/>Редактировать</Button><Button size="sm" variant={service.active?"danger":"secondary"} disabled={mutation.isPending} onClick={()=>mutation.mutate()}>{service.active?"Деактивировать":"Активировать"}</Button></div>{mutation.error&&<p className="mt-2 text-xs text-red-700">{errorMessage(mutation.error)}</p>}</td></tr>}
function ServiceDialog({value,close}:{value:ClinicService|null|"new";close:()=>void}){const client=useQueryClient();if(value===null)return null;return <Dialog open onOpenChange={open=>!open&&close()} title={value==="new"?"Новая услуга":"Редактировать услугу"}><ServiceForm key={value==="new"?"new":value.id} service={value==="new"?undefined:value} close={close} saved={async input=>{if(value==="new")await api("/api/services",{method:"POST",body:JSON.stringify(input)});else await api(`/api/services/${value.id}`,{method:"PUT",body:JSON.stringify(input)});await client.invalidateQueries({queryKey:["services"]});close()}}/></Dialog>}
function ServiceForm({service,close,saved}:{service?:ClinicService;close:()=>void;saved:(input:ClinicServiceInput)=>Promise<void>}){const[name,setName]=useState(service?.name??"");const[price,setPrice]=useState(String(service?.price??""));const[duration,setDuration]=useState(String(service?.durationMinutes??30));const[error,setError]=useState<string|null>(null);const[pending,setPending]=useState(false);async function submit(e:FormEvent){e.preventDefault();setPending(true);setError(null);try{await saved({name,price:Number(price),durationMinutes:Number(duration),active:service?.active??true})}catch(e){setError(errorMessage(e));setPending(false)}}return <form onSubmit={submit} className="space-y-4"><Field label="Название" value={name} set={setName} required/><Field label="Цена, сом" value={price} set={setPrice} type="number" min="0" step="0.01" required/><Field label="Длительность, минут" value={duration} set={setDuration} type="number" min="1" step="1" required/>{error&&<p className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="flex justify-end gap-2"><Button type="button" variant="secondary" onClick={close}>Отмена</Button><Button disabled={pending}>{pending?"Сохраняем…":"Сохранить"}</Button></div></form>}
function Field({label,value,set,type="text",required=false,min,step}:{label:string;value:string;set:(v:string)=>void;type?:string;required?:boolean;min?:string;step?:string}){return <label className="block text-sm font-medium text-slate-700">{label}<Input className="mt-2" type={type} value={value} onChange={e=>set(e.target.value)} required={required} min={min} step={step}/></label>}
