package com.dentalcrm.appointment;
import com.dentalcrm.common.*; import com.dentalcrm.doctor.*; import com.dentalcrm.patient.*; import com.dentalcrm.service.*; import com.dentalcrm.user.*; import org.springframework.security.access.AccessDeniedException; import org.springframework.security.core.Authentication; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.*; import java.util.*; import static com.dentalcrm.appointment.AppointmentDtos.*;
@Service @Transactional public class AppointmentManager {
 private final AppointmentRepository repo;private final AppointmentServiceItemRepository items;private final PatientService patients;private final DoctorService doctors;private final ClinicServiceManager services;private final UserRepository users;private final DoctorRepository doctorRepo;
 public AppointmentManager(AppointmentRepository r,AppointmentServiceItemRepository i,PatientService p,DoctorService d,ClinicServiceManager s,UserRepository u,DoctorRepository dr){repo=r;items=i;patients=p;doctors=d;services=s;users=u;doctorRepo=dr;}
 public AppointmentResponse create(AppointmentRequest r,Authentication auth){validateTime(r.startTime(),r.endTime());ensureDoctorAccess(r.doctorId(),auth);if(repo.hasConflict(r.doctorId(),r.startTime(),r.endTime(),null))throw new ConflictException("Doctor already has an overlapping appointment");Appointment a=new Appointment();a.setPatient(patients.get(r.patientId()));a.setDoctor(doctors.get(r.doctorId()));a.setStartTime(r.startTime());a.setEndTime(r.endTime());a.setStatus(r.status()==null?AppointmentStatus.SCHEDULED:r.status());a.setNotes(r.notes());a.setCreatedBy(users.findByUsernameIgnoreCase(auth.getName()).orElseThrow());repo.save(a);addServices(a,r.serviceIds());return map(a);}
 public AppointmentResponse update(Long id,AppointmentRequest r,Authentication auth){Appointment a=get(id);ensureDoctorAccess(a.getDoctor().getId(),auth);ensureDoctorAccess(r.doctorId(),auth);validateTime(r.startTime(),r.endTime());if(repo.hasConflict(r.doctorId(),r.startTime(),r.endTime(),id))throw new ConflictException("Doctor already has an overlapping appointment");a.setPatient(patients.get(r.patientId()));a.setDoctor(doctors.get(r.doctorId()));a.setStartTime(r.startTime());a.setEndTime(r.endTime());if(r.status()!=null)a.setStatus(r.status());a.setNotes(r.notes());items.deleteAll(items.findByAppointmentId(id));items.flush();addServices(a,r.serviceIds());return map(a);}
 public AppointmentResponse status(Long id,AppointmentStatus status,Authentication auth){Appointment a=get(id);ensureDoctorAccess(a.getDoctor().getId(),auth);if(status!=AppointmentStatus.CANCELLED&&status!=AppointmentStatus.NO_SHOW&&repo.hasConflict(a.getDoctor().getId(),a.getStartTime(),a.getEndTime(),id))throw new ConflictException("Doctor already has an overlapping appointment");a.setStatus(status);return map(a);}
 @Transactional(readOnly=true) public List<AppointmentResponse> list(OffsetDateTime from,OffsetDateTime to,Authentication auth){if(!to.isAfter(from))throw new IllegalArgumentException("to must be after from");var doctor=doctorRepo.findByUserUsername(auth.getName());var data=doctor.isPresent()?repo.findByDoctorIdAndStartTimeBetweenOrderByStartTime(doctor.get().getId(),from,to):repo.findByStartTimeBetweenOrderByStartTime(from,to);return data.stream().map(this::map).toList();}
 @Transactional(readOnly=true) public AppointmentResponse find(Long id,Authentication auth){Appointment a=get(id);ensureDoctorAccess(a.getDoctor().getId(),auth);return map(a);}
 private void addServices(Appointment a,List<Long> ids){if(ids==null)return;for(Long id:new LinkedHashSet<>(ids)){var s=services.get(id);if(!s.isActive())throw new IllegalArgumentException("Inactive service cannot be added: "+id);AppointmentServiceItem item=new AppointmentServiceItem();item.setAppointment(a);item.setService(s);item.setPrice(s.getPrice());items.save(item);}}
 private void validateTime(OffsetDateTime start,OffsetDateTime end){if(!end.isAfter(start))throw new IllegalArgumentException("endTime must be after startTime");}
 private void ensureDoctorAccess(Long doctorId,Authentication auth){boolean isAdmin=auth.getAuthorities().stream().anyMatch(x->x.getAuthority().equals("ROLE_ADMIN"));if(!isAdmin&&doctorRepo.findByUserUsername(auth.getName()).map(Doctor::getId).filter(doctorId::equals).isEmpty())throw new AccessDeniedException("Doctors may only manage their own appointments");}
 private Appointment get(Long id){return repo.findById(id).orElseThrow(()->new NotFoundException("Appointment not found: "+id));}
 private AppointmentResponse map(Appointment a){var serviceItems=items.findByAppointmentId(a.getId()).stream().map(i->new ServiceItemResponse(i.getId(),i.getService().getId(),i.getService().getName(),i.getPrice())).toList();return new AppointmentResponse(a.getId(),a.getPatient().getId(),a.getPatient().getFullName(),a.getDoctor().getId(),a.getDoctor().getUser().getFullName(),a.getStartTime(),a.getEndTime(),a.getStatus(),a.getNotes(),a.getCreatedAt(),a.getCreatedBy().getUsername(),serviceItems);}
}
