package com.dentalcrm.doctor;
import com.dentalcrm.common.ConflictException; import com.dentalcrm.user.*; import org.junit.jupiter.api.*; import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder; import java.util.*; import static org.junit.jupiter.api.Assertions.*; import static org.mockito.Mockito.*;
class DoctorServiceTest {private DoctorRepository doctors;private UserRepository users;private DoctorService service;private Doctor existing;
 @BeforeEach void setup(){doctors=mock(DoctorRepository.class);users=mock(UserRepository.class);when(users.save(any())).thenAnswer(i->{User u=i.getArgument(0);u.setId(1L);return u;});when(doctors.save(any())).thenAnswer(i->{Doctor d=i.getArgument(0);d.setId(2L);return d;});service=new DoctorService(doctors,users,new BCryptPasswordEncoder());User u=new User();u.setId(1L);u.setUsername("dentist");u.setFullName("Doctor One");u.setPasswordHash("old");u.setRole(Role.DOCTOR);u.setActive(true);existing=new Doctor();existing.setId(2L);existing.setUser(u);when(doctors.findById(2L)).thenReturn(Optional.of(existing));}
 @Test void createsDoctorAndUserTogetherWithBcryptAndDoctorRole(){var response=service.create(new UserDtos.CreateDoctorUserRequest("dentist2","password1","Doctor Two","Therapist","123"));var user=org.mockito.ArgumentCaptor.forClass(User.class);verify(users).save(user.capture());assertTrue(new BCryptPasswordEncoder().matches("password1",user.getValue().getPasswordHash()));assertEquals(Role.DOCTOR,user.getValue().getRole());assertTrue(user.getValue().isActive());assertEquals(2L,response.id());verify(doctors).save(any());}
 @Test void rejectsDuplicateUsername(){when(users.existsByUsernameIgnoreCase("dentist")).thenReturn(true);assertThrows(ConflictException.class,()->service.create(new UserDtos.CreateDoctorUserRequest("dentist","password1","Doctor One",null,null)));verify(doctors,never()).save(any());}
 @Test void editsProfileWithoutExposingOrChangingHash(){service.update(2L,new DoctorDtos.UpdateDoctorRequest("New Name","Surgeon","555"));assertEquals("New Name",existing.getUser().getFullName());assertEquals("old",existing.getUser().getPasswordHash());assertEquals("Surgeon",existing.getSpecialization());}
 @Test void deactivatesAndActivatesSameHistoricalProfile(){assertFalse(service.setActive(2L,false).active());assertFalse(existing.getUser().isActive());verify(doctors,never()).delete(any());assertTrue(service.setActive(2L,true).active());}
 @Test void resetPasswordUsesBcrypt(){service.resetPassword(2L,"newpass12");assertTrue(new BCryptPasswordEncoder().matches("newpass12",existing.getUser().getPasswordHash()));}
 @Test void activeOnlySelectionUsesRepositoryFilter(){when(doctors.findByUserActiveTrueOrderByUserFullName()).thenReturn(List.of(existing));assertEquals(1,service.findAll(true).size());verify(doctors).findByUserActiveTrueOrderByUserFullName();}
}
