package com.dentalcrm.doctor;
import com.dentalcrm.auth.UserSessionRegistry; import com.dentalcrm.common.ConflictException; import com.dentalcrm.user.*; import org.junit.jupiter.api.*; import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder; import java.util.*; import static org.junit.jupiter.api.Assertions.*; import static org.mockito.Mockito.*;
class DoctorServiceTest {private DoctorRepository doctors;private UserRepository users;private UserSessionRegistry sessions;private DoctorService service;private Doctor existing;
 @BeforeEach void setup(){doctors=mock(DoctorRepository.class);users=mock(UserRepository.class);sessions=mock(UserSessionRegistry.class);when(users.save(any())).thenAnswer(i->{User u=i.getArgument(0);u.setId(1L);return u;});when(doctors.save(any())).thenAnswer(i->{Doctor d=i.getArgument(0);d.setId(2L);return d;});service=new DoctorService(doctors,users,new BCryptPasswordEncoder(),sessions);User u=new User();u.setId(1L);u.setUsername("dentist");u.setFullName("Doctor One");u.setPasswordHash("old");u.setRole(Role.DOCTOR);u.setActive(true);existing=new Doctor();existing.setId(2L);existing.setUser(u);when(doctors.findById(2L)).thenReturn(Optional.of(existing));when(users.findByIdForUpdate(1L)).thenReturn(Optional.of(u));}
 @Test void createsDoctorAndUserTogetherWithBcryptAndDoctorRole(){var response=service.create(new UserDtos.CreateDoctorUserRequest("dentist2","password1","Doctor Two","Therapist","123"));var user=org.mockito.ArgumentCaptor.forClass(User.class);verify(users).save(user.capture());assertTrue(new BCryptPasswordEncoder().matches("password1",user.getValue().getPasswordHash()));assertEquals(Role.DOCTOR,user.getValue().getRole());assertTrue(user.getValue().isActive());assertEquals(2L,response.id());verify(doctors).save(any());}
 @Test void rejectsDuplicateUsername(){when(users.existsByUsernameIgnoreCase("dentist")).thenReturn(true);assertThrows(ConflictException.class,()->service.create(new UserDtos.CreateDoctorUserRequest("dentist","password1","Doctor One",null,null)));verify(doctors,never()).save(any());}
 @Test void editsProfileUnderUserLockWithoutChangingCredentials(){service.update(2L,new DoctorDtos.UpdateDoctorRequest("New Name","Surgeon","555"));assertEquals("New Name",existing.getUser().getFullName());assertEquals("old",existing.getUser().getPasswordHash());assertEquals("Surgeon",existing.getSpecialization());verify(users).findByIdForUpdate(1L);}
 @Test void deactivatesAndActivatesSameHistoricalProfile(){assertFalse(service.setActive(2L,false).active());assertFalse(existing.getUser().isActive());assertEquals(1,existing.getUser().getAuthVersion());verify(sessions).revokeAll("dentist");verify(doctors,never()).delete(any());assertTrue(service.setActive(2L,true).active());assertEquals(1,existing.getUser().getAuthVersion());}
 @Test void resetPasswordUsesBcryptAndSerializedVersionBump(){service.resetPassword(2L,"newpass12");assertTrue(new BCryptPasswordEncoder().matches("newpass12",existing.getUser().getPasswordHash()));assertEquals(1,existing.getUser().getAuthVersion());verify(users).findByIdForUpdate(1L);verify(sessions).revokeAll("dentist");service.resetPassword(2L,"otherpass12");assertEquals(2,existing.getUser().getAuthVersion());}
 @Test void activeDirectoryUsesRepositoryFilterAndSafeProjection(){when(doctors.findByUserActiveTrueOrderByUserFullName()).thenReturn(List.of(existing));var response=service.findActive();assertEquals(1,response.size());assertEquals(new DoctorDtos.ActiveDoctorResponse(2L,"Doctor One",null),response.getFirst());verify(doctors).findByUserActiveTrueOrderByUserFullName();}
 @Test void managementSelectionIncludesPrivateFields(){when(doctors.findAllByOrderByUserFullName()).thenReturn(List.of(existing));var response=service.findAll();assertEquals("dentist",response.getFirst().username());verify(doctors).findAllByOrderByUserFullName();}
 @Test void appointmentAssignmentUsesSameUserLockAsDeactivation(){assertSame(existing,service.getForAssignment(2L));verify(users).findByIdForUpdate(1L);}
}
